front:
    image: nginx:1.11.10
    ports:
        - "81:80"
    links:
        - "engine:engine"
    volumes:
        - ".:/home/docker:ro"
        - "./docker/front/default.conf:/etc/nginx/conf.d/default.conf:ro"
engine:
    build: ./docker/engine/dev/
    volumes:
        - ".:/home/docker:rw"
        - "./docker/engine/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro"
    links:
        - "db:db"
    working_dir: "/home/docker"

db:
    image: mysql:8.0.0
    ports:
        - "3307:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_USER=yannalpha
        - MYSQL_PASSWORD=Coincoin0160
        - MYSQL_DATABASE=database